---
- name: r1soft Playbook
  hosts: all
  become: true
  become_method: sudo
  connection: ssh
  ignore_errors: false
  tasks:
    - name: creates a repo 
      copy:
        src: r1soft.repo
        dest: /etc/yum.repo.d/r1soft.repo
    
    - name: install R1soft 
      package:
        name: serverbackup-enterprise-agent
        state: latest


    - name: Power off iptables
      systemd:
        name: firewalld
        state: stopped
      ignore_errors: true


    - name: Get Key 
      shell: r1soft-setup --get-key http://backup.atakanerdil.com



    - name: Start R1soft Agent
      systemd:
        name: sbm-agent
        state: restarted
        enabled: yes 

